# Generated by Django 6.0.6 on 2026-06-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cikkek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cikkNev', models.CharField(max_length=255, verbose_name='Cikk címe')),
                ('cikkImage', models.ImageField(blank=True, null=True, upload_to='cikkek_kepek/', verbose_name='Cikk képe')),
                ('cikkShortDescription', models.CharField(max_length=500, verbose_name='Rövid leírás')),
                ('cikkLongDescription', models.TextField(verbose_name='Hosszú leírás')),
            ],
        ),
        migrations.CreateModel(
            name='Egitestek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('egitestNev', models.CharField(max_length=200, verbose_name='Égitest neve')),
                ('egitestImage', models.ImageField(blank=True, null=True, upload_to='egitestek_kepek/', verbose_name='Égitest képe')),
                ('egitestDescription', models.TextField(verbose_name='Égitest leírása')),
            ],
        ),
        migrations.CreateModel(
            name='Esemenyek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esemenyNev', models.CharField(max_length=200, verbose_name='Esemény neve')),
                ('esemenyDatum', models.DateTimeField(verbose_name='Esemény dátuma és ideje')),
                ('esemenyHelyszin', models.CharField(max_length=255, verbose_name='Esemény helyszíne')),
            ],
        ),
    ]
