# Generated by Django 6.0.6 on 2026-06-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vremek', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cikkek',
            options={'verbose_name_plural': 'cikkek'},
        ),
        migrations.AlterModelOptions(
            name='egitestek',
            options={'verbose_name_plural': 'egitestek'},
        ),
        migrations.AlterModelOptions(
            name='esemenyek',
            options={'verbose_name_plural': 'esemenyek'},
        ),
        migrations.AddField(
            model_name='cikkek',
            name='cikkVideo',
            field=models.ImageField(blank=True, null=True, upload_to='cikkek_kepek/', verbose_name='Cikk video'),
        ),
        migrations.AddField(
            model_name='egitestek',
            name='egitestVideo',
            field=models.ImageField(blank=True, null=True, upload_to='egitestek_kepek/', verbose_name='Égitest video'),
        ),
    ]
