# Generated by Django 6.0.6 on 2026-06-28 18:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vremek', '0002_alter_cikkek_options_alter_egitestek_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='esemenyek',
            name='jelentkezok',
            field=models.ManyToManyField(blank=True, related_name='jelentkezett_esemenyek', to=settings.AUTH_USER_MODEL, verbose_name='Jelentkezett felhasználók'),
        ),
    ]
