# Generated by Django 6.0.6 on 2026-06-28 19:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vremek', '0003_esemenyek_jelentkezok'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cikkek',
            name='cikkVideo',
        ),
        migrations.AddField(
            model_name='cikkek',
            name='egitestVideo',
            field=models.FileField(blank=True, null=True, upload_to='egitestek_videok/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'mkv'])], verbose_name='Égitest videója'),
        ),
        migrations.AlterField(
            model_name='egitestek',
            name='egitestVideo',
            field=models.FileField(blank=True, null=True, upload_to='egitestek_videok/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'mkv', 'webm', 'vlc'])], verbose_name='Égitest videója'),
        ),
    ]
