# Generated by Django 6.0.6 on 2026-06-28 19:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vremek', '0004_remove_cikkek_cikkvideo_cikkek_egitestvideo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cikkek',
            name='egitestVideo',
        ),
        migrations.AddField(
            model_name='cikkek',
            name='cikkVideo',
            field=models.FileField(blank=True, null=True, upload_to='cikkek_videok/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'mkv', 'webm', 'vlc'])], verbose_name='Cikkek videója'),
        ),
    ]
