# Generated by Django 6.0.6 on 2026-06-28 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vremek', '0005_remove_cikkek_egitestvideo_cikkek_cikkvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cikkek',
            name='cikkImage',
            field=models.ImageField(blank=True, null=True, upload_to='static/cikkek_kepek/', verbose_name='Cikk képe'),
        ),
        migrations.AlterField(
            model_name='cikkek',
            name='cikkVideo',
            field=models.FileField(blank=True, null=True, upload_to='static/cikkek_videok/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'mkv', 'webm', 'vlc'])], verbose_name='Cikkek videója'),
        ),
        migrations.AlterField(
            model_name='egitestek',
            name='egitestImage',
            field=models.ImageField(blank=True, null=True, upload_to='static/egitestek_kepek/', verbose_name='Égitest képe'),
        ),
        migrations.AlterField(
            model_name='egitestek',
            name='egitestVideo',
            field=models.FileField(blank=True, null=True, upload_to='static/egitestek_videok/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'mkv', 'webm', 'vlc'])], verbose_name='Égitest videója'),
        ),
    ]
