# Generated by Django 6.0.6 on 2026-08-16 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vremek', '0007_alter_cikkek_cikkimage_alter_cikkek_cikkvideo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kommentek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tartalom', models.TextField(verbose_name='Komment tartalma')),
                ('letrehozva', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozás ideje')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kommentek', to=settings.AUTH_USER_MODEL, verbose_name='Felhasználó')),
            ],
            options={
                'verbose_name_plural': 'kommentek',
            },
        ),
    ]
